---
title: Esquema de preprocesamiento para detección de cambios (bosque)
---
flowchart TD
    gee1[(Catalogo de datos GEE)]
    Landsat8@{ shape: docs, label: Landsat 8-9 Level 2}
    Landsat7@{ shape: docs, label: Landsat 7 Level 2}
    Landsat5@{ shape: docs, label: Landsat 5 Level 2}
    Sentinel2@{ shape: docs, label: Sentinel 2 L2}
    MDE@{ shape: doc, label: Modelo digital de elevación}
    
    INS@{ shape: procs, label: "Identificación de nubes y sombras"}
    MNS@{ shape: docs, label: "Mascaras de nubes y sombras"}
    NT@{ shape: procs, label: "Normalización topográfica"}
    Combinacion1@{ shape: hex, label: "Recorte y combinación" }
    Combinacion2@{ shape: cross-circ, label: "Promedios de bandas" }

    BSecas2000@{ shape: docs, label: 2000 Secas}
    BLluvias2000@{ shape: docs, label: 2000 Lluvias}
    BSecas2010@{ shape: docs, label: 2010 Secas}
    BLluvias2010@{ shape: docs, label: 2010 Lluvias}
    BSecas2020@{ shape: docs, label: 2020 Secas}
    BLluvias2020@{ shape: docs, label: 2020 Lluvias}

    IndVeg2000@{ shape: procs, label: "NDVI e indices"}
    IndVeg2010@{ shape: procs, label: "NDVI e indices"}
    IndVeg2020@{ shape: procs, label: "NDVI e indices"}
    Tass2000@{ shape: procs, label: "Tasseled Cap"}
    Tass2010@{ shape: procs, label: "Tasseled Cap"}
    Tass2020@{ shape: procs, label: "Tasseled Cap"}

    Comb2000@{ shape: cross-circ, label: "Combinación" }
    Comb2010@{ shape: cross-circ, label: "Combinación" }
    Comb2020@{ shape: cross-circ, label: "Combinación" }

    Est2000@{ shape: procs, label: "Estandarización"}
    Est2010@{ shape: procs, label: "Estandarización"}
    Est2020@{ shape: procs, label: "Estandarización"}

    Capas2000@{ shape: docs, label: "Predictores 2000"}
    Capas2010@{ shape: docs, label: "Predictores 2010"}
    Capas2020@{ shape: docs, label: "Predictores 2020"}

    PCA2020@{ shape: hex, label: "PCA"}
    TL2000@{ shape: hex, label: "Transf. lineal"}
    TL2010@{ shape: hex, label: "Transf. lineal"}

    CapasPCA2000@{ shape: docs, label: "PC 2000"}
    CapasPCA2010@{ shape: docs, label: "PC 2010"}
    CapasPCA2020@{ shape: docs, label: "PC 2020"}

    Eigenvectors@{ shape: win-pane, label: "Matriz Eigenvectores" }

    gee1---|selección|Landsat8
    gee1---|selección|Landsat7
    gee1---|selección|Landsat5
    gee1---|selección|Sentinel2
    gee1---MDE

    subgraph preprocesamiento
        Landsat8-->INS
        Landsat7-->INS
        Landsat5-->INS

        MDE-->NT
        Landsat8-->NT
        Landsat7-->NT
        Landsat5-->NT

        INS-->MNS
        NT-->Combinacion1
        MNS-->Combinacion1
        Combinacion1---|promedios|Combinacion2
        
    end

    Combinacion2---->BSecas2000
    Combinacion2---->BLluvias2000
    Combinacion2---->BSecas2010
    Combinacion2---->BLluvias2010
    Combinacion2---->BSecas2020
    Combinacion2---->BLluvias2020

    subgraph 2000
        BSecas2000-->IndVeg2000
        BLluvias2000-->Tass2000
        BLluvias2000-->IndVeg2000
        BSecas2000-->Tass2000
        IndVeg2000-->Comb2000
        Tass2000-->Comb2000
        Comb2000-->Est2000
        Est2000-->Capas2000
        Capas2000-->TL2000
        TL2000-->CapasPCA2000
    end

    subgraph 2010
        BSecas2010-->IndVeg2010
        BLluvias2010-->Tass2010
        BLluvias2010-->IndVeg2010
        BSecas2010-->Tass2010
        IndVeg2010-->Comb2010
        Tass2010-->Comb2010
        Comb2010-->Est2010
        Est2010-->Capas2010
        Capas2010-->TL2010
        TL2010-->CapasPCA2010
    end

    subgraph 2020
        BSecas2020-->IndVeg2020
        BSecas2020-->Tass2020
        BLluvias2020-->IndVeg2020
        BLluvias2020-->Tass2020
        IndVeg2020-->Comb2020
        Tass2020-->Comb2020
        Comb2020-->Est2020
        Est2020-->Capas2020
        Capas2020---->PCA2020
        PCA2020-->CapasPCA2020
    end

    PCA2020---->Eigenvectors
    Eigenvectors---->TL2000
    Eigenvectors---->TL2010
    
    
    
    
