---
title: Esquema de clasificación para detección de cambios (bosque)
---
flowchart TD
    PC2000@{ shape: docs, label: PC2000}
    PC2010@{ shape: docs, label: PC2010}
    PC2020@{ shape: docs, label: PC2020}
    Ref2020@{ shape: doc, label: Referencia2020}
    Muestreo@{ shape: proc, label: Muestreo}
    Subset@{ shape: hex, label: Subdivision}
    Train2020@{ shape: win-pane, label: Conjunto entrenamiento}
    Test2020@{ shape: win-pane, label: Conjunto control}
    Valid2020@{ shape: win-pane, label: Conjunto validación}

    Hyperparam@{ shape: win-pane, label: Hiperparámetros}
    TrainSVM@{ shape: proc, label: Entrenamiento SVM}
    TrainANN@{ shape: proc, label: Entrenamiento ANN}
    ModeloSVM@{ shape: double-circle, label: Modelo SVM}
    ModeloANN@{ shape: double-circle, label: Modelo ANN}
    ModeloSVMok@{ shape: double-circle, label: Modelo SVM ajustado}
    ModeloANNok@{ shape: double-circle, label: Modelo ANN ajustado}
    ValidSVM@{ shape: proc, label: Validación SVM}
    ValidANN@{ shape: proc, label: Validación ANN}
    OptimSVM@{ shape: diam, label: SVM optimo?}
    OptimANN@{ shape: diam, label: ANN optimo?}
    ControlSVM@{ shape: proc, label: Evaluación SVM}
    ControlANN@{ shape: proc, label: Evaluación ANN}
    AjusteHyp@{ shape: proc, label: Ajuste Hyperp.}

    PC2020 --> Muestreo
    Ref2020 --> Muestreo
    Muestreo --> Subset
    Subset --70%--> Train2020
    Subset --15%--> Test2020
    Subset --15%--> Valid2020

    Hyperparam ----> TrainSVM
    Hyperparam ----> TrainANN

    subgraph SVM
        Train2020 --> TrainSVM
        TrainSVM --> ModeloSVM
        ModeloSVM --> ValidSVM
        ValidSVM --> OptimSVM
        OptimSVM --si--> ModeloSVMok
        ModeloSVMok --> ControlSVM
    end

    subgraph ANN
        Train2020 --> TrainANN
        TrainANN --> ModeloANN
        ModeloANN --> ValidANN
        ValidANN --> OptimANN
        OptimANN --si--> ModeloANNok
        ModeloANNok --> ControlANN
    end

    
    
    
    
    
    Valid2020 --> ValidSVM
    Valid2020 --> ValidANN
    
    
    
    
    OptimSVM --no--> AjusteHyp
    OptimANN --no--> AjusteHyp
    AjusteHyp ----> Hyperparam
    
    
    Test2020 --> ControlSVM
    Test2020 --> ControlANN
    


    
    
