---
title: Esquema de preprocesamiento para detección de cambios (bosque)
---
flowchart TD
    gee1[(Catalogo de datos GEE)]
    Landsat8@{ shape: docs, label: Landsat 8-9 Level 2}
    Landsat7@{ shape: docs, label: Landsat 7 Level 2}
    Landsat5@{ shape: docs, label: Landsat 5 Level 2}
    Sentinel2@{ shape: docs, label: Sentinel 2 L2 complementario}
    MDE@{ shape: doc, label: Modelo digital de elevación}
    
    INS@{ shape: procs, label: "Identificación de nubes y sombras"}
    MNS@{ shape: docs, label: "Mascaras de nubes y sombras"}
    NT@{ shape: procs, label: "Normalización topográfica"}
    Combinacion@{ shape: hex, label: "Promedios de bandas por fecha y periodo del año aplicando mascaras" }


    gee1---|selección|Landsat8
    gee1---|selección|Landsat7
    gee1---|selección|Landsat5
    gee1---|selección|Sentinel2
    gee1---MDE

    subgraph main
        Landsat8-->INS
        Landsat7-->INS
        Landsat5-->INS

        MDE-->NT
        Landsat8-->NT
        Landsat7-->NT
        Landsat5-->NT

        INS-->MNS
        NT-->Combinacion
        MNS-->Combinacion
    end
