flowchart TD
  A1([Definicion de zona de analisis])-->B1
  B1[/Definir coordenadas UTM del centro, coordenadas de extremos LLC y URC, zona UTM CRS/]-->C1
  C1[Definición del rectangulo para descarga de imagenes de satelite: Colab ee]-->C2
  C1-->B3
  B2[/Definir densidad de muestreo de control/]-->B3
  B3[Definición aleatoria de zonas de referencia y de su enumeración: GEE]-->B4
  B4[Separación de definición de zonas de referencia en conjuntos de tamaño permitido por GEE]-->B5
  B5[[Descarga de conjuntos de zonas de referencia en formato KML]]-->B6
  B6[(Zonas de referencia en KML en Google Drive)]-->B7
  B6-->ANN11A
  B7[/Recolecta de información del estado de campo en cuadrantes de referencia en 2000, 2010 y 2020 por medio de captura por un experto/]-->B8
  B8[(Tabla CSV de estados de superficie en zonas de referencia en 2000, 2010 y 2020 según la nomenclatura de clases)]-->Z6

  C2[[Segmentación del rectangulo en zonas permitidos para descarga por GEE: Colab ee]]-->D1
  C2-->C3
  C2-->C4
  D04[(World Settlement Footprint 2015, Marconcini et al. 2020)]-->C3
  C3[[Descarga de segmentos de capa re referencia de urbanización en 2015 y su conversión en numpy array: Colab ee]]-->E4
  D05[(GLO-30: Global 30m Digital Elevation Model)]-->C4
  C4[[Descarga de segmentos de capa cuerpos de agua WBM en 2015 y su conversión en numpy array: Colab ee]]-->C5
  C5[[Unión y reetiquetado de variables por segmento según esquema de tres categorías]]-->C6
  C6[[Union de numpy arrays de los segmentos variable categorica en array completo de referencia 2015: Colab numpy]]-->E4
  E4[[Exportación a Google Drive]]-->E4A
  D01[(USGS Landsat 8 Level 2, Collection 2, Tier 1 LANDSAT_LC08_C02_T1_L2)]-->D1
  D02[(USGS Landsat 5 Level 2, Collection 2, Tier 1 LANDSAT_LT05_C02_T1_L2)]-->D1
  D03[(Harmonized Sentinel-2 MSI: MultiSpectral Instrument, Level-2A COPERNICUS_S2_SR_HARMONIZED)]-->D1
  D1[Selección de imagenes de satelite L5, L8 y Sentinel 2 para fechas de interés en 2000, 2010, 2015, 2020]-->D2
  D2{{Evaluación de calidad de la imagen/pixeles *nubes, sombra, reflectividad, valores faltantes}}
  D2--imagen/pixel con calidad suficiente disponible-->E1
  D2--imagen/pixel con calidad suficiente no disponible-->D3
  D3[/Toma de imagen/pixel de fecha alternativa/]-->D1
  E1[[Descarga de los segmentos de la imagen de GEE y su conversion en numpu array: Colab ee]]-->E2
  E2[[Union de numpy arrays de los segmentos en array completo por fecha: Colab numpy]]-->E3
  E3[[Exportación a Google Drive]]-->E3A
  E3A[(Base de datos de numpy arrays de variables predictoras que corresponden a las bandas de imagenes L5, L8 y Sentinel 2: Google Drive)]-->F1
  E4A[(Base de datos de numpy arrays de variables con etiquetas categoricas conocidas en 2015: Google Drive)]-->F1
  F1[Separación de subconjuntos 2015 de entranamiento, validación 10% y control 10%: Colab scipy]--80%-->F2A
  F1--10%-->F2B
  F1--10%-->F2C
  F2A[(Datos de entrenamiento 2015)]--ANN-->ANN1
  F2B[(Datos de validación 2015)]--ANN-->ANN2
  F2C[(Datos de control 2015)]
  F2A--SVM-->SVM1
  F2A-->J2
  F2B-->J2
  F2C-->J2
  J2[[Convoluton]]==>J3
  J3[[Pooling]]--CNN-->CNN1
  H1[/Conjuntos de hiperparámetros a probar/]-->ANN1
  H1-->CNN1
  H1-->SVM1

  ANN1[[Entrenamiento de ANN en varias temporadas: Colab TensorFlow]]-->ANN2
  ANN2[[Prediccion con ANN: Colab TensorFlow]]-->ANN3
  ANN3[[Evaluación de modelo con datos de validacion]]-->ANN4
  ANN4{{Hiperparametros óptimos}}--si-->ANN5
  ANN4--no-->ANN4A
  ANN4A[[Ajuste de hiperparámetros]]-->ANN1
  ANN5[Guardar el objeto de modelo 2015 en Google Drive: Colab TensorFlow]-->ANN6
  ANN5-->ANN6A
  ANN5-->ANN10
  ANN6[Evaluación de modelo con datos de control 2015]-->ANN7
  ANN6A[Prediccion con datos 2015: Colab TensorFlow]-->ANN8
  ANN7[/Reporte modelo 2015 de ACC, AUC, TSS, Kappa, F1 por clase/]
  ANN8[/Capa categorica para 2015 de espacio construido, espacio no-construido y agua/]-->ANN9
  ANN8-->Z4
  ANN10[[predicción con ANN datos 2020: Colab TensorFlow]]-->ANN10A
  ANN10A[/Capa categorica para 2020 de espacio construido, espacio no-construido y agua/]-->Z4
  
  CNN1[[Entrenamiento CNN en varias temporadas]]
  CNN2[[Prediccion con CNN: Colab TensorFlow]]-->CNN3
  CNN3[[Evaluación de modelo con datos de validacion]]-->CNN4
  CNN4{{Hiperparametros óptimos}}--si-->CNN5
  CNN4--no-->CNN4A
  CNN4A[[Ajuste de hiperparámetros]]-->CNN1
  CNN5[Guardar el objeto de modelo 2015 en Google Drive: Colab TensorFlow]-->CNN6
  CNN5-->CNN6A
  CNN6[Evalouación de modelo con datos de control 2015]-->CNN7
  CNN6A[Prediccion con datos 2015]-->CNN8
  CNN7[/Reporte modelo 2015 de ACC, AUC, TSS, Kappa, F1 por clase/]
  CNN8[/Capa categorica para 2015 de espacio construido, espacio no-construido y agua/]-->CNN9
  CNN9[Guardar en Google Drive prediccion categorica 2015 como numpy array: Colab numpy]-->Z4


  SVM1[[Entrenamiento SVM]]-->SVM2
  SVM2[[Prediccion con SVM: Colab]]-->SVM3
  SVM3[[Evaluación de modelo con datos de validacion]]-->SVM4
  SVM4{{Hiperparametros óptimos}}--si-->SVM5
  SVM4--no-->SVM4A
  SVM4A[[Ajuste de hiperparámetros]]-->SVM1
  SVM5[Guardar el objeto de modelo 2015 en Google Drive: Colab]-->SVM6
  SVM5-->SVM6A
  SVM6[Evalouación de modelo con datos de control 2015]-->SVM7
  SVM6A[Prediccion con datos 2015]-->SVM8
  SVM7[/Reporte modelo 2015 de ACC, AUC, TSS, Kappa, F1 por clase/]
  SVM8[/Capa categorica para 2015 de espacio construido, espacio no-construido y agua/]-->SVM9
  SVM9[Guardar en Google Drive prediccion categorica 2015 como numpy array: Colab numpy]-->Z4

  M1[/Capa categorica para 2020 de espacio construido, espacio no-construido y agua/]-->Z1
  M2[/Capa categorica para 2010 de espacio construido, espacio no-construido y agua/]-->Z1
  M3[/Capa categorica para 2000 de espacio construido, espacio no-construido y agua/]-->Z1

  Z1[[Guardar en Google Drive como numpy array: Colab numpy]]-->Z2
  Z2[[Exportar en Google Drive como GeoTIFF: Colab]]-->END
  Z2-->Z4
  Z4[(Base de datos de numpy arrays y GeoTIFFs de espacio construido en 2000, 2010, 2015 y 2020)]

  Z5[[Descarga de GeoTIFF de predicción en 2000, 2010, 2020]]-->Z6
  Z6[[Extraccion de datos de predicción en zonas de referencia: R]]-->Z7
  Z7[[Evalouación de modelo con datos de control externos]]-->Z8A
  Z7-->Z8B
  Z7-->Z8C
  Z8A[/Reporte modelo 2020 de ACC, AUC, TSS, Kappa, F1 por clase/]-->END
  Z8B[/Reporte modelo 2010 de ACC, AUC, TSS, Kappa, F1 por clase/]-->END
  Z8C[/Reporte modelo 2000 de ACC, AUC, TSS, Kappa, F1 por clase/]-->END

  END([Estimación de mancha urbana de la zona concluida])
