flowchart TD
  subgraph ["Evaluacion de precisión externa]
    Z8A[/Reporte modelo 2020 de ACC, AUC, TSS, Kappa, F1 por clase/]
    Z8B[/Reporte modelo 2010 de ACC, AUC, TSS, Kappa, F1 por clase/]
    Z8C[/Reporte modelo 2000 de ACC, AUC, TSS, Kappa, F1 por clase/]
  
  START2([Datos de referencia de etapa anterior])
  START2-->B6
  START2-->B8

  B6[(Zonas de referencia en KML en Google Drive)]
  B6-->Z6
  B8[(Tabla CSV de estados de superficie en zonas de referencia en 2000, 2010 y 2020 según la nomenclatura de clases)]
  B8-->Z7

  Z4[(Base de datos de numpy arrays y GeoTIFFs de espacio construido en 2000, 2010, 2015 y 2020)]-->Z5
  Z5[[Descarga de GeoTIFF de predicción en 2000, 2010, 2020]]-->Z6

  Z6[[Extraccion de datos de predicción en zonas de referencia: R]]-->Z7
  Z7[[Evaluación de modelo con datos de control externos: R]]-->Z8A
  Z7-->Z8B
  Z7-->Z8C
  Z8A-->END
  Z8B-->END
  Z8C-->END

  END([Estimación de mancha urbana de la zona concluida])
