flowchart TD
  A1([Definicion de zona de analisis])-->B1
  B1[/Definir coordenadas UTM del centro, coordenadas de extremos LLC y URC, zona UTM CRS/]-->C1
  C1[Definición del rectangulo para descarga de imagenes de satelite: Colab ee]-->C2
  C1-->B3
  C2[[Segmentación del rectangulo en zonas permitidos para descarga por GEE: Colab ee]]-->D1
  B2[/Definir densidad de muestreo de control/]-->B3
  B3[Definición aleatoria de zonas de referencia y de su enumeración: GEE]-->B4
  B4[Separación de definición de zonas de referencia en conjuntos de tamaño permitido por GEE]-->B5
  B5[[Descarga de conjuntos de zonas de referencia en formato KML]]-->B6
  B6[(Zonas de referencia en KML en Google Drive)]
  C2-->C3
  C2-->C4
  D04[(World Settlement Footprint 2015, Marconcini et al. 2020)]-->C3
  C3[[Descarga de segmentos de capa re referencia de urbanización en 2015 y su conversión en numpy array: Colab ee]]-->E4
  D05[(GLO-30: Global 30m Digital Elevation Model)]-->C4
  C4[[Descarga de segmentos de capa cuerpos de agua WBM en 2015 y su conversión en numpy array: Colab ee]]-->C5
  C5[[Unión y reetiquetado de variables por segmento según esquema de tres categorías]]-->C6
  C6[[Union de numpy arrays de los segmentos variable categorica en array completo de referencia 2015: Colab numpy]]-->E4
  E4[[Exportación a Google Drive]]-->E4A
  D01[(USGS Landsat 8 Level 2, Collection 2, Tier 1 LANDSAT_LC08_C02_T1_L2)]-->D1
  D02[(USGS Landsat 5 Level 2, Collection 2, Tier 1 LANDSAT_LT05_C02_T1_L2)]-->D1
  D03[(Harmonized Sentinel-2 MSI: MultiSpectral Instrument, Level-2A COPERNICUS_S2_SR_HARMONIZED)]-->D1
  D1[Selección de imagenes de satelite L5, L8 y Sentinel 2 para fechas de interés en 2000, 2010, 2015, 2020]-->D2
  D2{{Evaluación de calidad de la imagen/pixeles *nubes, sombra, reflectividad, valores faltantes}}
  D2--imagen/pixel con calidad suficiente disponible-->E1
  D2--imagen/pixel con calidad suficiente no disponible-->D3
  D3[/Toma de imagen/pixel de fecha alternativa/]-->D1
  E1[[Descarga de los segmentos de la imagen de GEE y su conversion en numpu array: Colab ee]]-->E2
  E2[[Union de numpy arrays de los segmentos en array completo por fecha: Colab numpy]]-->E3
  E3[[Exportación a Google Drive]]-->E3A
  E3A[(Base de datos de numpy arrays de variables predictoras que corresponden a las bandas de imagenes L5, L8 y Sentinel 2: Google Drive)]-->F1
  E4A[(Base de datos de numpy arrays de variables con etiquetas categoricas conocidas en 2015: Google Drive)]-->F1
  F1[Separación de subconjuntos 2015 de entranamiento, validación 10% y control 10%: Colab scipy]--80%-->F2A
  F1--10%-->F2B
  F1--10%-->F2C
  F2A[(Datos de entrenamiento 2015)]--ANN-->ANN1
  F2B[(Datos de validación 2015)]
  F2C[(Datos de control 2015)]
  F2A--SVM-->SVM1
  F2A--CNN-->J2
  J2[Convoluton]-->J3
  J3[Pooling]--CNN1
  H1[/Hiperparémetros iniciales/]-->ANN1
  H1-->CNN1
  H1-->SVM1
  ANN1[[Entrenamiento de ANN en varias temporadas: Colab TensorFlow]]-->ANN2
  ANN2[[Prediccion con ANN: Colab TensorFlow]]-->M1
  CNN1[[Entrenamiento CNN en varias temporadas]]
  SVM1[[Entrenamiento SVM]]
  M1[/Capa categorica para 2020 de espacio construido, espacio no-construido y agua/]-->Z1
  M2[/Capa categorica para 2010 de espacio construido, espacio no-construido y agua/]-->Z1
  M3[/Capa categorica para 2000 de espacio construido, espacio no-construido y agua/]-->Z1
  Z1[[Guardar en Google Drive como numpy array: Colab numpy]]-->Z2
  Z2[[Exportar en Google Drive como GeoTIFF: Colab]]-->Z3
  Z2-->Z4
  Z4[(Base de datos de numpy arrays y GeoTIFFs de espacio construido en 2000, 2010 y 2020)]
  Z3([Estimación de mancha urbana de la zona concluida])
