flowchart TD
  H1[/Conjuntos de hiperparámetros a probar/]
  H1-->ANN1
  H1-->CNN1
  H1-->SVM1

  E3A[(Base de datos de numpy arrays de variables predictoras que corresponden a las bandas de imagenes L5, L8 y Sentinel 2 en 2000, 2010, 2015, 2020: Google Drive)]
  E3A-->MODEL4
  E3A-->MODEL6
  F2A[(Datos de entrenamiento 2015: ANN y SVM)]
  F2A-->ANN1
  F2B[(Datos de validación 2015: ANN y SVM)]
  F2B-->ANN3
  F2C[(Datos de control 2015: ANN y SVM)]
  F2C-->MODEL2
  F3A[(Datos de entrenamiento 2015: CNN)]
  F3A-->ANN1
  F3B[(Datos de validación 2015: CNN)]
  F3B-->ANN3
  F3C[(Datos de control 2015: CNN)]
  F3C-->MODEL2
  B8[(Tabla CSV de estados de superficie en zonas de referencia en 2000, 2010 y 2020 según la nomenclatura de clases)]

  ANN1[[Entrenamiento de ANN, CNN o SVM en varias temporadas: Colab TensorFlow y/o SVM]]-->ANN2
  ANN2[[Prediccion con datos de validacion]]-->ANN3
  ANN3[[Evaluación de modelo con datos de validacion]]-->ANN4
  ANN4{{Hiperparametros óptimos}}--si-->MODEL1
  ANN4--no-->ANN4A
  ANN4A[[Ajuste de hiperparámetros]]-->ANN1
 
  MODEL1[[Guardar el objeto de modelo 2015 en Google Drive]]-->MODEL2
  MODEL1-->MODEL4
  MODEL1-->MODEL6
  MODEL2[[Prediccion con datos de control 2015]]-->MODEL3
  MODEL3[[Evaluación de modelo con datos de control 2015]]-->MODEL3A
  MODEL3A[/Reporte modelo 2015 de ACC, AUC, TSS, Kappa, F1 por clase/]
  MODEL4[[Prediccion con datos completos 2015]]-->MODEL5
  MODEL5[/Capa categorica para 2015 de espacio construido, espacio no-construido y agua/]-->Z1
  MODEL6[[predicción con datos 2020]]-->MODEL7
  MODEL7[/Capa categorica para 2020 de espacio construido, espacio no-construido y agua/]-->Z1

  Z1[[Guardar en Google Drive como numpy array: Colab numpy]]-->Z2
  Z2[[Exportar en Google Drive como GeoTIFF: Colab]]-->Z4
  Z2-->Z4
  Z4[(Base de datos de numpy arrays y GeoTIFFs de espacio construido en 2000, 2010, 2015 y 2020)]-->END

  Z5[[Descarga de GeoTIFF de predicción en 2000, 2010, 2020]]-->Z6
  Z6[[Extraccion de datos de predicción en zonas de referencia: R]]-->Z7
  Z7[[Evalouación de modelo con datos de control externos]]-->Z8A
  Z7-->Z8B
  Z7-->Z8C
  Z8A[/Reporte modelo 2020 de ACC, AUC, TSS, Kappa, F1 por clase/]-->END
  Z8B[/Reporte modelo 2010 de ACC, AUC, TSS, Kappa, F1 por clase/]-->END
  Z8C[/Reporte modelo 2000 de ACC, AUC, TSS, Kappa, F1 por clase/]-->END
  END([Estimación de mancha urbana de la zona concluida])
