flowchart TD
  A1([Definicion de zona de analisis])-->B1
  B1[/Definir coordenadas UTM del centro, coordenadas de extremos LLC y URC, zona UTM (CRS)/]-->C1
  C1[Definición de rectangulo para descarga de imagenes de satelite (Colab ee)]-->C2
  C2[[Segmentación del rectangulo en zonas permitidos para descarga de GEE (Colab ee)]]-->D1
  D1[Selección de imagenes de satelite L5 y L8 para cada fecha de interés (2000, 2010, 2020)]-->D2
  D2{{Evaluación de disponibilidad y calidad de la imagen}}
  D2--imagen con calidad suficiente disponible-->E1
  D2--imagen con calidad suficiente no disponible-->D3
  D3[/Cambio de fecha a una cercana/]-->D1
  E1[Descarga de segmentos de la imagen y su conversion en numpu array]-->J1
  J1{{Verificación de prerequisitos para arranque de analisis ANN}}-->K1
  K1[Analisis con ANN]-->M1
  M1[/Capa categorica de espacio construido, espacio no-construido y agua/]-->Z1
  Z1([Analisis de zona concluido])
