flowchart TD
  subgraph s1["Precisión externa"]
    Z8A[/Reporte modelo 2020 de ACC, AUC, TSS, Kappa, F1 por clase/]
    Z8B[/Reporte modelo 2010 de ACC, AUC, TSS, Kappa, F1 por clase/]
    Z8C[/Reporte modelo 2000 de ACC, AUC, TSS, Kappa, F1 por clase/]
  end

  START2([Datos de referencia de etapa anterior])
  START2-->B6
  START2-->B8

  B6[(Zonas de referencia en KML en Google Drive)]
  B6-->Z6
  B8[(Tabla CSV de estados de superficie en zonas de referencia en 2000, 2010 y 2020 según la nomenclatura de clases)]
  B8-->Z7

  Z4[(Base de datos de numpy arrays y GeoTIFFs de espacio construido en 2000, 2010, 2015 y 2020)]-->Z5
  Z4-->Z5A
  Z5[[Descarga de GeoTIFF de predicción en 2000, 2010, 2020]]-->Z6
  Z5A[[Carga de GeoTIFF de prediccion en GEE Assets]]-->CLASS1
  Z5A-->CLASS11

  Z6[[Extraccion de datos de predicción en zonas de referencia: R]]-->Z7
  Z7[[Evaluación de modelo con datos de control externos: R]]-->Z8A
  Z7-->Z8B
  Z7-->Z8C
  Z8A-->END
  Z8B-->END
  Z8C-->END

  END([Estimación de mancha urbana de la zona concluida])

  CLASS1[[Clasificcion banaria construido/no-construido: GEE]]-->CLASS2
  CLASS1-->CLASS3
  CLASS2[[Calculo de promedios de 0 y 1 en un radio la capa binaria en radio 584 m]]-->CLASS3
  CLASS3[[Reclasificar pixeles del espacio construido en urbanos, suburbanos y rurales]]-->CLASS4
  CLASS3-->R1
  CLASS3-->CLASS5
  R1[(Capa de urbano-suburbano-rural)]
  CLASS4[[Identificar solo pixeles urbanos y suburbanos]]-->CLASS4A
  CLASS4A[[Calculo de maximos en un radio de capa binaria en radio 100 m]]-->CLASS5
  CLASS5[[Reclasificar pixeles urbanos-suburbanos-rurales-marginal]]-->CLASS6
  CLASS5-->CLASS11
  CLASS6[[Vectorizar espacio abierto no-marginal]]-->CLASS7
  CLASS7[[Calcular areas de poligonos de espaci abierto]]-->CLASS8
  CLASS8[[Filtrar poligonos menores que 200 Ha]]-->CLASS9
  CLASS9[[Etiquetar poligonos segun tamaño como abierto capturado y rural]]-->CLASS10
  CLASS10[[Rasterizar poligonos de espacio abierto etiquetado]]-->CLASS11
  CLASS11[[Reclasificar poligonos de espacio urbano y abierto en 7 categorias]]-->R2
  R2[(Capa de clasificacion urbano-suburbano-rural de 7 categorias)]
